### ISSUE TITLE
Give error when trying to open a non default browser

### ISSUE THREAD

**Issue by chriswiley** [coderfe/vscode-open-in-browser#12]
I am using Windows 10 Contributor's Update and VSCode  Insiders version 1.13.0. With the open-in-browser 0.1.0 update I get this error message. Opening the default doesn't throw an error.

![error open in browser](https://cloud.githubusercontent.com/assets/497447/26523454/e7dd1cf8-42e5-11e7-88f4-ab4b8730b84f.PNG)

**Comment by coderfee** [comment]
I have released a new version, please update to the latest version @chriswiley 😄

**Comment by chriswiley** [comment]
Works great now! Thank you!
