### ISSUE TITLE
Ctl Alt D - Not working on Ubuntu

### ISSUE THREAD

**Issue by dafyNZ** [coderfe/vscode-open-in-browser#6]
I have just installed Open In Browser v0.0.8 onto Ubuntu 16.04 and tried Ctl Alt D to open/run project in my current defualt browser (Firefox) but nothing happens. I already have firefox open. 

If I Ctl Alt O and select Firefox it works.

**Comment by coderfee** [comment]
Shortcut keys conflict, it seems I have to change the shortcut keys.

**Comment by coderfee** [comment]
Now, open html in default browser with <kbd>Ctrl</kbd>+<kbd>K</kbd> <kbd>D</kbd>. @dafyNZ
