### ISSUE TITLE
I'm not sure if I am using it incorrectly  :D

### ISSUE THREAD

**Issue by MikuGhoul** [coderfe/vscode-open-in-browser#9]
Use `"ctrl+alt+o"` means open this HTML file by brower,right?
But when I use this keyboard shortcut **second time**,the brower display the **first time HTML file**.
And the third time the same.
Did I use it incorrectly?

**Comment by MikuGhoul** [comment]
BTW,vsc version is 1.12.2

**Comment by coderfee** [comment]
I have released a new version, please update to the latest version.

**Comment by MikuGhoul** [comment]
THX。BUG repaired   ：D
